### ISSUE TITLE
fused_layer_norm_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at7getTypeERKNS_6TensorE

### ISSUE THREAD

**Issue by xijiz** [huggingface/pytorch-transformers#1093]
## 🐛 Bug

Model I am using (Bert, XLNet....): BERT

Language I am using the model on (English, Chinese....): English

The problem arise when using:
* [ ] the official example scripts: (give details)
* [ * ] my own modified scripts: (give details)

The tasks I am working on is:
* [ ] an official GLUE/SQUaD task: (give the name)
* [ * ] my own task or dataset: (give details)

## To Reproduce

1.
2.
3.

## Environment

* OS: ubuntu 18.04
* Python version: 3.6
* PyTorch version: 1.1
* PyTorch Transformers version (or branch): master
* Using GPU ? Yes
* Distributed of parallel setup ? Yes
* Any other relevant information: No

## Additional context

Traceback (most recent call last):
  File "./src/run_experiments.py", line 97, in <module>
    run_all_tasks(parameters.config)
  File "/workspace/code/src/utils/util.py", line 37, in wrapped_func
    func(*args, **kwargs)
  File "./src/run_experiments.py", line 84, in run_all_tasks
    trainer = Trainer(opt)
  File "/workspace/code/src/trainer.py", line 76, in __init__
    self._model = DecisionMaker(self._opt["model"], numb)
  File "/workspace/code/src/model.py", line 43, in __init__
    self._intt = Intuition(self._opt["intt"])
  File "/workspace/code/src/intteng/intt.py", line 16, in __init__
    config=config
  File "/opt/conda/lib/python3.6/site-packages/pytorch_transformers/modeling_utils.py", line 403, in from_pretrained
    model = cls(config)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_transformers/modeling_bert.py", line 650, in __init__
    self.embeddings = BertEmbeddings(config)
  File "/opt/conda/lib/python3.6/site-packages/pytorch_transformers/modeling_bert.py", line 253, in __init__
    self.LayerNorm = BertLayerNorm(config.hidden_size, eps=config.layer_norm_eps)
  File "/opt/conda/lib/python3.6/site-packages/apex/normalization/fused_layer_norm.py", line 127, in __init__
    fused_layer_norm_cuda = importlib.import_module("fused_layer_norm_cuda")
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /opt/conda/lib/python3.6/site-packages/fused_layer_norm_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at7getTypeERKNS_6TensorE

**Comment by xijiz** [comment]
> I am afraid we won't be able to help you if you do not provide any information on what caused the problem.

I am sorry that I provided the incompleted information. I have sovled this problem by changing the cuda version.

**Comment by Ahmedn1** [comment]
@xijiz which version did you change to? and which version did you use? Because I have this same issue with CUDA 10
