### ISSUE TITLE
XLNet resize embedding size ERROR

### ISSUE THREAD

**Issue by Saner3** [huggingface/pytorch-transformers#1124]
## ❓ Questions & Help

I add new tokens to XLNetLMHeadModel and use resize function
```
tokenizer.add_tokens(["<token1>", "<token2>"])
model.resize_token_embeddings(len(tokenizer))
```
But when running, the following error occurs:
```
Traceback (most recent call last):
 ...
  File "/nas/home/jsun/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "../pytorch_transformers/modeling_xlnet.py", line 1059, in forward
    logits = self.lm_loss(transformer_outputs[0])
  File "/nas/home/jsun/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/nas/home/jsun/.local/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 92, in forward
    return F.linear(input, self.weight, self.bias)
  File "/nas/home/jsun/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1410, in linear
    output += bias
RuntimeError: The size of tensor a (32003) must match the size of tensor b (32000) at non-singleton dimension 2
```

It is because in `resize_token_embeddings`, it changes the embedding size and calls `tie_weight` function to resize the LM head weight. But it forgot to change the size of `bias`, since XLNet has 
```
self.lm_loss = nn.Linear(config.d_model, config.n_token, bias=True)
```
while other models have bias=False

**Comment by thomwolf** [comment]
Should be fixed on master by @LysandreJik's PR!
