### ISSUE TITLE
extract_features

### ISSUE THREAD

**Issue by zhangatao** [huggingface/pytorch-transformers#611]
Traceback (most recent call last):
  File "extract_features.py", line 297, in <module>
    main()
  File "extract_features.py", line 230, in main
    tokenizer = BertTokenizer.from_pretrained(args.bert_model, do_lower_case=args.do_lower_case)
  File "/home/py36/lib/python3.6/site-packages/pytorch_pretrained_bert/tokenization.py", line 197, in from_pretrained
    tokenizer = cls(resolved_vocab_file, *inputs, **kwargs)
  File "/home/py36/lib/python3.6/site-packages/pytorch_pretrained_bert/tokenization.py", line 97, in __init__
    self.vocab = load_vocab(vocab_file)
  File "/home/py36/lib/python3.6/site-packages/pytorch_pretrained_bert/tokenization.py", line 56, in load_vocab
    token = reader.readline()
  File "/home/py36/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

Hello, the pre-trained model I downloaded from https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz, what caused the above error?

**Comment by rajarsheem** [comment]
Were you able to fix this issue? If yes, can you please share your solution?
